DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects(
    id BIGSERIAL PRIMARY KEY,
    pr_name VARCHAR(255) NOT NULL,
    cu_name VARCHAR(255) NOT NULL,
    pr_owner VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    init_invest VARCHAR(80) NOT NULL,
    nre_hours VARCHAR(80) NOT NULL,
    ongo_headcount VARCHAR(80) NOT NULL,
    ongo_scrap VARCHAR(80) NOT NULL,
    ongo_spareparts VARCHAR(80) NOT NULL,
    ongo_overhead VARCHAR(80) NOT NULL,
    savings_headcount VARCHAR(80) NOT NULL,
    savings_scrap VARCHAR(80) NOT NULL,
    savings_costavoidance VARCHAR(80) NOT NULL,
    dri_safety VARCHAR(80) NOT NULL,
    dri_quality VARCHAR(80) NOT NULL,
    dri_capacity VARCHAR(80) NOT NULL,
    dri_customerreq VARCHAR(80) NOT NULL,
    pr_status VARCHAR(80) NOT NULL,
    capex_po BOOLEAN,
    aware BOOLEAN,
    pr_start_date TIMESTAMP(0) NOT NULL,
    pr_finish_date TIMESTAMP(0) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL
);

INSERT INTO projects(
    pr_name,
    cu_name,
    pr_owner,
    email,
    init_invest,
    nre_hours,
    ongo_headcount,
    ongo_scrap,
    ongo_spareparts,
    ongo_overhead,
    savings_headcount,
    savings_scrap,
    savings_costavoidance,
    dri_safety,
    dri_quality,
    dri_capacity,
    dri_customerreq ,
    pr_status,
    capex_po,
    aware,
    pr_start_date,
    pr_finish_date,
    created_at,
    updated_at
)
VALUES(
    'Automatic O-ring',
    'Tandem',
    'Yair Montoya',
    'yair.montoya@flex.com',
    '250000',
    '25000',
    '1000',
    '1000',
    '1000',
    '1000',
    '10000',
    '10000',
    '10000',
    'No Impact',
    'No Impact',
    'No Impact',
    'No Impact',
    'Concept',
    'true',
    'true',
    '2022-07-14',
    '2022-07-14',
    '2022-07-14',
    '2022-07-14'
)